name: CD devops exam

on:
  push:
    branches: [master]
    workflow_dispatch:

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - run: npm ci
      - run: npm run
      - uses: w9jds/firebase-action/@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
