name: DevOps examen

on:
  pull_request:
    branches: [master]

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.14
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run prettier
